version: '2.4'
services:
  newspews-database:
    # port 5432
    networks:
      - backend

  newspews-pgadmin:
    image: dpage/pgadmin4:6.4
    container_name: newspews-pgadmin
    restart: always
    env_file:
      - ./env/pga-variables.env
    environment:
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    volumes:
      - ./volumes/pga:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-8081}:80'
    networks:
      - default
      - backend
    depends_on:
      newspews-database:
        condition: service_healthy

  newspews-reverse-proxy:
    image: nginx:1.20.1-alpine
    container_name: newspews-reverse-proxy
    volumes:
      - ./config/nginx/html:/etc/nginx/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - '${PROXY_PORT:-8080}:80'
    networks:
      - default
      - frontend
    depends_on:
      - newspews-api
      - newspews-web

  newspews-web:
    image: ghcr.io/somprasongd/newspews-web:${WEB_VERSION:-latest}
    container_name: newspews-web
    restart: always
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - newspews-api
    networks:
      - frontend

  newspews-api:
    image: ghcr.io/somprasongd/newspews-api:${API_VERSION:-latest}
    container_name: newspews-api
    restart: always
    env_file:
      - ./env/api-variables.env
    environment:
      - TZ=Asia/Bangkok
    networks:
      - frontend
      - backend
    depends_on:
      newspews-database:
        condition: service_healthy

networks:
  default:
    external:
      name: webproxy
  frontend:
  backend:
