name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build WASM
        run: |
          cd server/cmd/wasm
          GOOS=js GOARCH=wasm go build -o ../../../client/public/newspews.wasm
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ../../../client/public/

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: |
          cd client
          npm ci

      - name: Build UI
        run: |
          cd client
          npm run build
          npm run export
          touch ./out/.nojekyll
          touch ./out/_next/.nojekyll
        env:
          BASE_URL: /newspews
          NEXT_PUBLIC_USE_GEO: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./client/out
